name: eleu-bot
dependencies:
- msvc_runtime=1.0.1=0
- pip=7.1.2=py35_0
- python=3.5.1=0
- requests=2.9.0=py35_0
- setuptools=19.1.1=py35_0
- wheel=0.26.0=py35_1
- pip:
  - tinydb==3.0.0
  - websockets==2.7

