name: eleu-bot
dependencies:
- msvc_runtime=1.0.1=0
- pip=7.1.2=py35_0
- python=3.5.1=0
- requests=2.9.0=py35_0
- setuptools=19.1.1=py35_0
- wheel=0.26.0=py35_1
- pip:
  - gspread==0.3.0
  - httplib2==0.9.2
  - oauth2client==1.5.2
  - pyasn1==0.1.9
  - pyasn1-modules==0.0.8
  - rsa==3.2.3
  - six==1.10.0
  - tinydb==3.0.0
  - websockets==2.7

