IRC_SERVER = 'irc.freenode.net'
IRC_CHANNEL = '#learnprogramming'
IRC_NAME = 'ForwardMsgsFromSlack'

DATABASE_URI = ''
SESSION_ID = ''

SLACK_TOKEN = ''

# delay between outgoing messages in seconds
SLACK_MSG_DELAY = 1

CH_GENERAL = 'C0H0Q0J3D'
CH_TALKINGBOTS = 'C0H0SR40J'
CH_DM_ME = 'D0HDXTHE2'
CH_NEW_USER_FEEDBACK = 'G0K7J19C0'
CH_IRC_CHAT = 'C0G183XU5'
CH_PROGRAMMING = 'C0H0MG0F6'
CH_ANNOUNCEMENTS = 'C0G16K1M2'
CH_ADMIN_HELP = 'C0H0MG1FW'
CH_PYTHON = 'C0H0T0EUE'
CH_C_SHARP = 'C0H0T0EQ6'
CH_RUBY = 'C0H0NQV29'
CH_SWIFT = 'C0H0MG0KE'
CH_WEB = 'C0H0MG11S'
CH_JAVA = 'C0H0MFZUL'
CH_CPP = 'C0H0SR4CS'
CH_GAMEDEV = 'C0H0MG19A'
CH_HASKELL = 'C0SMCMJ0H'

LOG_FILE = 'database/log.out'
LOG_LEVEL = 'debug'  # 'debug' | 'info' | 'error'
